from __future__ import annotations

REPLAY_VERSION = "v3.3-deterministic-replay"

STRATEGIES = [
    "CIO_CURRENT_POLICY",
    "BUY_AND_HOLD_PORTFOLIO",
    "CASH_FORTRESS_ONLY",
    "EQUAL_WEIGHT_HELD",
    "SPY_BENCHMARK",
    "QQQ_BENCHMARK",
    "GOLD_MINERS_SLEEVE",
    "VOL_HEDGE_SLEEVE",
    "HIGH_BETA_SLEEVE",
    "STR_KELLY_ADVISORY",
    "PEI_EVENT_GATED",
    "RISK_OVERLAY_ADJUSTED",
]

SCENARIOS = [
    "BASE_CASE",
    "WARSH_HAWKISH_RATES_UP",
    "BOJ_YEN_CARRY_UNWIND",
    "GLOBAL_LEVERAGE_UNWIND",
    "GOLD_PEACE_DIVIDEND",
    "HIGH_BETA_RISK_OFF",
    "VOL_SPIKE",
    "LIQUIDITY_RECOVERY",
    "SOFT_LANDING_RISK_ON",
]

